/* USERS: */
INSERT INTO USERS (ID, NAME, TITLE) VALUES ('1', 'Naor1', 'VP');
INSERT INTO USERS (ID, NAME, TITLE) VALUES ('2', 'Naor2', 'Cleaner'); 
INSERT INTO USERS (ID, NAME, TITLE) VALUES ('3', 'Naor3', 'Software Engineer'); 

/* PERMISSIONS: */
INSERT INTO PERMISSIONS (ID, DESCRIPTION) VALUES ('1', 'READ');
INSERT INTO PERMISSIONS (ID, DESCRIPTION) VALUES ('2', 'WRITE');
INSERT INTO PERMISSIONS (ID, DESCRIPTION) VALUES ('3', 'ADMIN');
INSERT INTO PERMISSIONS (ID, DESCRIPTION) VALUES ('4', 'READ/WRITE');

/* USER_PERMISSION: */
INSERT INTO USER_PERMISSION (USER_ID, PERMISSION_ID) VALUES ('1','1');
INSERT INTO USER_PERMISSION (USER_ID, PERMISSION_ID) VALUES ('1','2');
INSERT INTO USER_PERMISSION (USER_ID, PERMISSION_ID) VALUES ('1','3');
INSERT INTO USER_PERMISSION (USER_ID, PERMISSION_ID) VALUES ('2','4');
